import localFont from "next/font/local";
import "./globals.css";

const ppneueMontreal = localFont({
  src: "./fonts/ppneuemontreal-book.otf",
  variable: "--font-medium",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/ppneuemontreal-book.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ppneueMontreal.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
